#!/bin/zsh #-x

# build and start engine & build:start:monitor app

d1=engine
[ -d "${d1}" ] || { echo "directory ${d1} not found"; exit 1; }

d2=app
[ -d "${d1}" ] || { echo "directory ${d1} not found"; exit 1; }

pushd ${d1}
npm run docker:stop
npm run docker:build
npm run docker:start
popd

pushd ${d2}
npm run bdsm
popd


